### ISSUE TITLE
react-native start failing

### ISSUE THREAD

**Issue by kewp** [ZackLeonardo/react-native-metro-grid#1]
when trying to start the development server I get an error

c:\Users\Karl\tst\react-native-metro-grid\Example>react-native start
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

c:\Users\Karl\tst\react-native-metro-grid\Example>

**Comment by kewp** [comment]
I fixed it by changing a few lines in run-package.js https://gist.github.com/mqli/e1e6576e9838d885a43a

**Comment by kewp** [comment]
Still getting an error on my emulator - Unable to download JS bundle.

**Comment by ZackLeonardo** [comment]
thanks.
